import {
  attribute,
  autoGeneratedHashKey,
  rangeKey,
  table
} from "@aws/dynamodb-data-mapper-annotations";
import uuidV4 = require("uuid/v4");
import { DatabaseEnum } from "../";

@table(DatabaseEnum.Table)
export class Customer {
  @autoGeneratedHashKey()
  id: string;

  @rangeKey({ defaultProvider: () => new Date() })
  createdAt?: Date;

  @attribute()
  isPremium?: boolean;

  @attribute()
  ifVip?: boolean;

  @attribute()
  firstName?: string;

  @attribute()
  lastName?: string;
}
